-- Flyway Migration V4 - Unified Prefixed Schema for CVFacil.NG
-- This script provides absolute isolation and robustness by using 'cv_' prefix

-- 1. cv_users
CREATE TABLE IF NOT EXISTS "cv_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(255) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP WITH TIME ZONE
);

-- 2. cv_resumes
CREATE TABLE IF NOT EXISTS "cv_resumes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "profession" VARCHAR(255),
    "contact_email" VARCHAR(255),
    "phone" VARCHAR(50),
    "website" VARCHAR(255),
    "photo_url" TEXT,
    "layout_id" VARCHAR(50) DEFAULT 'dark-blue',
    "summary" TEXT,
    "is_public" BOOLEAN DEFAULT FALSE,
    "is_primary" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_resumes_user FOREIGN KEY ("user_id") REFERENCES "cv_users"("id") ON DELETE CASCADE
);

-- 3. cv_experiences
CREATE TABLE IF NOT EXISTS "cv_experiences" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resume_id" BIGINT NOT NULL,
    "company" VARCHAR(255) NOT NULL,
    "job_position" VARCHAR(255) NOT NULL,
    "start_date" VARCHAR(255),
    "end_date" VARCHAR(255),
    "description" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_experiences_resume FOREIGN KEY ("resume_id") REFERENCES "cv_resumes"("id") ON DELETE CASCADE
);

-- 4. cv_educations
CREATE TABLE IF NOT EXISTS "cv_educations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resume_id" BIGINT NOT NULL,
    "institution" VARCHAR(255) NOT NULL,
    "degree" VARCHAR(255) NOT NULL,
    "field_of_study" VARCHAR(255),
    "start_date" VARCHAR(255),
    "end_date" VARCHAR(255),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_educations_resume FOREIGN KEY ("resume_id") REFERENCES "cv_resumes"("id") ON DELETE CASCADE
);

-- 5. cv_skills
CREATE TABLE IF NOT EXISTS "cv_skills" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resume_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "percentage" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skills_resume FOREIGN KEY ("resume_id") REFERENCES "cv_resumes"("id") ON DELETE CASCADE
);

-- 6. cv_languages
CREATE TABLE IF NOT EXISTS "cv_languages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resume_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "level" VARCHAR(100),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_languages_resume FOREIGN KEY ("resume_id") REFERENCES "cv_resumes"("id") ON DELETE CASCADE
);

-- 7. cv_hobbies
CREATE TABLE IF NOT EXISTS "cv_hobbies" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resume_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hobbies_resume FOREIGN KEY ("resume_id") REFERENCES "cv_resumes"("id") ON DELETE CASCADE
);
